<script setup lang="ts">
import { computed, ref } from 'vue'

type Clip = { id: number; title: string; type: 'video' | 'fx' | 'text'; start: number; length: number; color: string }
const clips = ref<Clip[]>([
  { id: 1, title: 'CITY_PLATE_01', type: 'video', start: 1, length: 28, color: '#7d70ff' },
  { id: 2, title: 'NEON REFLECTIONS', type: 'fx', start: 12, length: 18, color: '#f65cae' },
  { id: 3, title: 'BES / CINEFORGE', type: 'text', start: 32, length: 23, color: '#69d8ff' },
  { id: 4, title: 'TITANIUM GRADE', type: 'video', start: 58, length: 25, color: '#a59bfd' },
])
const selected = ref(1), playing = ref(false), playhead = ref(24), search = ref('')
const history = ref<Clip[][]>([]), future = ref<Clip[][]>([])
const activeTab = ref('Inspector'), toast = ref('')
const filtered = computed(() => effects.filter(e => e.toLowerCase().includes(search.value.toLowerCase())))
const selectedClip = computed(() => clips.value.find(c => c.id === selected.value))
const effects = ['Preset Intelligence', 'Cost Intelligence', 'QA Engine', 'KPI Engine · 42 metrics', 'Batch analysis', 'Model recovery']
function snapshot() { history.value.push(structuredClone(clips.value)); future.value = [] }
function undo() { const previous = history.value.pop(); if (previous) { future.value.push(structuredClone(clips.value)); clips.value = previous } }
function redo() { const next = future.value.pop(); if (next) { history.value.push(structuredClone(clips.value)); clips.value = next } }
function addEffect(name: string) { snapshot(); clips.value.push({ id: Date.now(), title: name.toUpperCase(), type: 'fx', start: 40, length: 15, color: '#f65cae' }); toast.value = `${name} added to timeline`; setTimeout(() => toast.value = '', 2000) }
function drop(event: DragEvent) { const id = Number(event.dataTransfer?.getData('clip')); if (!id) return; const clip = clips.value.find(c => c.id === id); if (!clip) return; snapshot(); const box = (event.currentTarget as HTMLElement).getBoundingClientRect(); clip.start = Math.max(0, Math.round((event.clientX - box.left) / box.width * 90)); }
function exportProject() { const data = JSON.stringify({ name: 'Analytics Command Center', fps: 24, clips: clips.value }, null, 2); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([data], { type: 'application/json' })); a.download = 'cineforge-project.json'; a.click(); toast.value = 'Project JSON exported'; setTimeout(() => toast.value = '', 2000) }
</script>

<template>
  <main>
    <header class="topbar"><div class="brand"><span class="brand-mark">B</span><b>BES</b><span>ANALYTICS OS</span></div><div class="project-name">Analytics Command Center <span>⌄</span></div><div class="header-actions"><button class="ghost" @click="undo" :disabled="!history.length">↶</button><button class="ghost" @click="redo" :disabled="!future.length">↷</button><button class="outline" @click="exportProject">Export report</button><button class="render">Live <b>SYNC</b> ↗</button></div></header>
    <section class="workspace">
      <aside class="library"><div class="section-heading"><span>ANALYTICS OS</span><button>＋</button></div><div class="search">⌕ <input v-model="search" placeholder="Search knowledge" /></div><div class="nav"><div class="nav-active">✦ &nbsp; Intelligence <small>Responses API · MCP</small></div><div>▣ &nbsp; Event stream</div><div>◌ &nbsp; Workflow DNA <em>14</em></div><div>✧ &nbsp; Knowledge graph <em>248</em></div></div><div class="asset-title">ACTIVE INTELLIGENCE</div><button v-for="effect in filtered" :key="effect" class="asset" @click="addEffect(effect)"><i></i><span>{{ effect }}<small>Event-sourced signal</small></span><b>＋</b></button><div class="automation"><div class="spark">✦</div><b>OpenAI orchestrator</b><p>Responses API coordinates memory, QA, and workflow intelligence.</p><button>Open control plane →</button></div></aside>
      <section class="center"><div class="viewer"><div class="viewer-top"><span>REAL-TIME PERFORMANCE</span><span>WEBSOCKET CONNECTED · 1.2s</span></div><div class="frame"><div class="glow"></div><div class="city"></div><div class="type"><small>INTELLIGENCE STATUS</small><strong>92.4%<br><em>HEALTH SCORE</em></strong><i></i></div><div class="safe"></div><div class="metric-float"><b>+18.6%</b><span>render efficiency</span></div><div class="timecode">EVENTS · 24,281</div></div><div class="transport"><button @click="playing = !playing">{{ playing ? '❚❚' : '▶' }}</button><span>◁</span><div class="scrub"><i :style="{width: `${playhead}%`}"></i></div><span>▷</span><b>1:00:00</b></div></div>
        <div class="timeline"><div class="timeline-head"><div><b>Live event timeline</b><span>24 fps</span></div><div><button @click="undo">Undo</button><button @click="redo">Redo</button><button>⌘ Snap</button></div></div><div class="ruler"><span v-for="n in 10" :key="n">00:{{ String(n * 10).padStart(2,'0') }}</span></div><div class="tracks" @dragover.prevent @drop="drop"><div class="track-label"><span>▸ V1</span><small>CineForge</small></div><div class="track-lane"><div v-for="clip in clips.filter(c=>c.type==='video')" :key="clip.id" draggable="true" @dragstart="e => e.dataTransfer?.setData('clip', String(clip.id))" @click="selected = clip.id" class="clip" :class="{selected: selected===clip.id}" :style="{left:clip.start+'%',width:clip.length+'%',background:clip.color}">{{clip.title}}</div></div><div class="track-label"><span>✦ FX</span><small>Intelligence</small></div><div class="track-lane"><div v-for="clip in clips.filter(c=>c.type==='fx')" :key="clip.id" draggable="true" @dragstart="e => e.dataTransfer?.setData('clip', String(clip.id))" @click="selected = clip.id" class="clip fx" :class="{selected: selected===clip.id}" :style="{left:clip.start+'%',width:clip.length+'%',background:clip.color}">{{clip.title}}</div></div><div class="track-label"><span>T &nbsp;V2</span><small>Chatium</small></div><div class="track-lane"><div v-for="clip in clips.filter(c=>c.type==='text')" :key="clip.id" draggable="true" @dragstart="e => e.dataTransfer?.setData('clip', String(clip.id))" @click="selected = clip.id" class="clip text" :class="{selected: selected===clip.id}" :style="{left:clip.start+'%',width:clip.length+'%',background:clip.color}">{{clip.title}}</div></div><div class="playhead" :style="{left:playhead+'%'}"></div></div></div>
      </section>
      <aside class="inspector"><div class="tabs"><button v-for="t in ['Inspector','Workflow']" :class="{on:activeTab===t}" @click="activeTab=t">{{t}}</button></div><template v-if="activeTab==='Inspector'"><div class="ins-title"><span>SELECTED SIGNAL</span><b>•••</b></div><div class="clip-card"><div class="thumb"></div><div><b>{{ selectedClip?.title }}</b><small>{{ selectedClip?.type === 'fx' ? 'ComfyUI · Generated' : 'Project event' }}</small></div></div><label>Event source <select><option>CineForge / renderer</option><option>Chatium / audience</option><option>Batch API / archive</option></select></label><label>Confidence <span>100%</span><input type="range" value="100"></label><label>Workflow DNA</label><div class="numbers"><button>X&nbsp; 0.00</button><button>Y&nbsp; 0.00</button><button>Scale&nbsp; 100</button><button>Rotation&nbsp; 0°</button></div><div class="ai-panel"><span>✦ SELF-HEALING ANALYTICS</span><p>Detects model changes, validates metric drift, and repairs affected presets.</p><button>Run QA repair →</button></div></template><template v-else><div class="ins-title"><span>WORKFLOW DNA</span></div><div class="node purple">Events <b>append-only project stream</b></div><div class="wire"></div><div class="node pink">Memory <b>Vector Store retrieval</b></div><div class="wire"></div><div class="node blue">QA Engine <b>preset improvement loop</b></div><button class="run">Run intelligence workflow →</button></template></aside>
    </section><div v-if="toast" class="toast">✓ {{toast}}</div>
  </main>
</template>
